#!/usr/bin/env python

import ds9samp
import sys

if len(sys.argv) == 1:
    print("""
dget: ds9.get()

Usage:  dget [xpa get commands]
""")
    exit()

with ds9samp.ds9samp() as ds9:
    
    cmd = ' '.join(sys.argv[1:])
    result = ds9.get(cmd)
    print(result)
