#!/usr/bin/env python

import sys
import astropy.io.fits as pyfits
import ds9samp
import numpy as np

args = sys.argv.copy()

HELP = """
Mark a circular region at the central DS9 window position

Usage options:

    $ dmark [-r=10] [-c=cyan] [-s] [Label text]
    $ dmark [--radius=10] [--color=cyan] [--select] [Label text]

"""

for a in args:
    if a in ["-h", "--help"]:
        print(HELP)
        exit()

pop_args = []

verbose = True
for a in args:
    if a in ["-q", "--quiet"]:
        pop_args.append(a)
        verbose = False

color = None
for a in args:
    if a.startswith("--color") | a.startswith("-c"):
        pop_args.append(a)
        if "=" in a:
            color = a.split("=")[1]
        else:
            color = "magenta"

select = False
for a in args:
    if a.startswith("--select") | a.startswith("-s"):
        pop_args.append(a)
        select = True

size = 10
for a in args:
    if a.startswith("--radius") | a.startswith("-r"):
        pop_args.append(a)
        if "=" in a:
            size = float(a.split("=")[1])

for arg in pop_args:
    if arg in args:
        args.pop(args.index(arg))

if len(args) > 1:
    mark_text = " ".join(args[1:])
else:
    mark_text = None

with ds9samp.ds9samp() as ds9:
    
    xy = ds9.get("pan image").split()
    ds9.set("region system image")
    
    if select:
        ds9.set("region select all")

    cmd = f"region command {{circle({xy[0]}, {xy[1]}, {size})"
    
    extra = []
    if mark_text is not None:
        extra.append(f"text='{mark_text}'")

    if color is not None:
        extra.append(f"color={color}")
    
    if len(extra) > 0:
        cmd += "# " + " ".join(extra)
    
    cmd += "}"
    print(cmd)

    ds9.set(cmd)

    if select:
        ds9.set("region select invert")


    