#!/usr/bin/env python

import os
import sys
import ds9samp

args = sys.argv.copy()

HELP = """
Wrapper around locking DS9 frame parameters

Usage:  dmatch [wcs]

 - frame lock [wcs, image, etc]
 - lock colorbar
 - match scale
 - frame single

"""

for a in args:
    if a in ["-h", "--help"]:
        print(HELP)
        exit()

if len(args) > 1:
    lock_frame = args[1]
else:
    lock_frame = "image"

with ds9samp.ds9samp() as ds9:
    
    ds9.set(f"frame lock {lock_frame}")
    ds9.set("lock colorbar")
    ds9.set("match scale")
    
