#!/usr/bin/env python

import sys
import astropy.io.fits as pyfits
import ds9samp
import numpy as np

args = sys.argv.copy()

HELP = """
Autoscale a DS9 window

Usage options:

    $ dscale scale
    $ dscale min max bkg
    $ dscale min max bkg scale
    $ dscale [...] [-q] [--quiet]  #  suppress messages
    $ dscale [...] --auto[=20]     #  compute median, NMAD scale (default: NMAD x 20)
    
"""

for a in args:
    if a in ["-h", "--help"]:
        print(HELP)
        exit()

pop_args = []

verbose = True
for a in args:
    if a in ["-q", "--quiet"]:
        pop_args.append(a)
        verbose = False

if verbose:
    pop_args.append("--verbose")

mi = -0.1
ma = 10

bkg = 0.
scale = 1.

auto_sigma = None

for i, a in enumerate(args):
    if a.startswith("--auto"):
        pop_args.append(a)
        if "=" in a:
            auto_sigma = float(a.split("=")[1])
        else:
            auto_sigma = 20

if auto_sigma is not None:
    
    with ds9samp.ds9samp() as ds9:
        data_ = ds9.retrieve_array()

    mask = (data_ != 0) & np.isfinite(data_)

    auto_bkg = np.nanmedian(data_[mask])
    
    nmad = 1.48 * np.nanmedian(np.abs(data_[mask] - auto_bkg))
    
    auto_scale = auto_sigma * nmad

    if verbose:
        sh = data_.shape
        
        msg = f"auto: ({sh[0]},{sh[1]})  µ = {auto_bkg:.2f}, s = {auto_scale:.2f} x {auto_sigma:.1f}"
        print(msg)

else:
    auto_bkg = auto_scale = None

for arg in pop_args:
    if arg in args:
        args.pop(args.index(arg))

if len(args) == 2:
    scale = float(args[1])

if len(args) >= 3:
    mi, ma = [float(a) for a in args[1:3]]

if len(args) >= 4:
    mi, ma, bkg = [float(a) for a in args[1:4]]

if len(args) >= 5:
    mi, ma, bkg, scale = [float(a) for a in args[1:5]]

# if verbose:
#     print(f"{len(args)} {mi} {ma} {bkg} {scale}")

if auto_bkg is not None:
    bkg = auto_bkg

if auto_scale is not None:
    scale *= auto_scale

limits = [float(v*scale + bkg) for v in [mi, ma]]

commands = [
    "scale log",
    "scale log exp 1000",
    "cmap value 5.45833 0.376694",
    f"scale limits {limits[0]} {limits[1]}",
]

with ds9samp.ds9samp() as ds9:
    
    for cmd in commands:
        if verbose:
            print(cmd)

        ds9.set(cmd)
    