#!/usr/bin/env python

import ds9samp
import sys

if len(sys.argv) == 1:
    print("""
dset: ds9.set()

Usage:  dset [xpa set commands]
""")
    exit()

with ds9samp.ds9samp() as ds9:
    
    cmd = ' '.join(sys.argv[1:])
    result = ds9.set(cmd)
    if result is not None:
        print(result)
    
